#!/usr/bin/env node
/**
 * Regenerates the auto-generated section of PLANNED.md by scanning all
 * git-tracked files for CODETAG comments (TODO/FIXME/HACK/XXX/NOTE).
 *
 * Usage:
 *   node scripts/generate-planned.mjs          # rewrite PLANNED.md in place
 *   node scripts/generate-planned.mjs --check  # exit 1 if PLANNED.md is stale
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';

export const CODETAGS = ['TODO', 'FIXME', 'HACK', 'XXX', 'NOTE'];

export const START_MARKER = '<!-- codetag-scan:start (everything below is overwritten) -->';
export const END_MARKER = '<!-- codetag-scan:end -->';

// Docs that *describe* the codetag convention would show up as false
// positives, and binary assets cannot contain comments.
const EXCLUDED_PATHS = [
	/^PLANNED\.md$/,
	/^AGENTS\.md$/,
	/^CLAUDE\.md$/,
	/^README\.md$/,
	/^DEVELOPMENT\.md$/,
	/^\.claude\//,
	/^scripts\/generate-planned\./,
	/^package-lock\.json$/,
	/\.(png|jpe?g|gif|ico|webp|avif|stl|woff2?|ttf|otf|pdf)$/i
];

const TAG_PATTERN = new RegExp(
	`(?:^|[^A-Za-z])(${CODETAGS.join('|')})(?:\\(([^)]*)\\))?:\\s*(\\S.*)`
);

/** Extracts codetag entries from one file's content. Exported for tests. */
export function extractCodetags(content, file) {
	const entries = [];
	content.split('\n').forEach((line, index) => {
		const match = line.match(TAG_PATTERN);
		if (!match) return;
		entries.push({
			tag: match[1],
			owner: match[2] || undefined,
			text: match[3].replace(/\s*(-->|\*\/|}?\s*\/>)?\s*$/, '').trim(),
			file,
			line: index + 1
		});
	});
	return entries;
}

/** Renders the markdown for the auto-generated section. Exported for tests. */
export function renderSection(entries) {
	const lines = [
		START_MARKER,
		'',
		'## Codetags found in the codebase',
		'',
		'Regenerated by `npm run planned` (also runs on every build and commit).',
		''
	];
	if (entries.length === 0) {
		lines.push('No codetags found. 🎉', '');
	}
	for (const tag of CODETAGS) {
		const tagged = entries.filter((entry) => entry.tag === tag);
		if (tagged.length === 0) continue;
		lines.push(`### ${tag}`, '');
		for (const entry of tagged) {
			const owner = entry.owner ? ` _(${entry.owner})_` : '';
			lines.push(`- \`${entry.file}:${entry.line}\`${owner} — ${entry.text}`);
		}
		lines.push('');
	}
	lines.push(END_MARKER);
	return lines.join('\n');
}

function trackedFiles() {
	return execFileSync('git', ['ls-files'], { encoding: 'utf8' })
		.split('\n')
		.filter(Boolean)
		.filter((file) => !EXCLUDED_PATHS.some((pattern) => pattern.test(file)));
}

function main() {
	const check = process.argv.includes('--check');
	const entries = trackedFiles().flatMap((file) => {
		try {
			return extractCodetags(readFileSync(file, 'utf8'), file);
		} catch {
			return [];
		}
	});

	const current = readFileSync('PLANNED.md', 'utf8');
	const start = current.indexOf(START_MARKER);
	const end = current.indexOf(END_MARKER);
	if (start === -1 || end === -1) {
		console.error(`PLANNED.md is missing the ${START_MARKER} / ${END_MARKER} markers.`);
		process.exit(1);
	}

	const next =
		current.slice(0, start) + renderSection(entries) + current.slice(end + END_MARKER.length);

	if (check) {
		if (next !== current) {
			console.error('PLANNED.md is stale. Run `npm run planned` and commit the result.');
			process.exit(1);
		}
		console.log('PLANNED.md is up to date.');
		return;
	}

	if (next !== current) {
		writeFileSync('PLANNED.md', next);
		console.log(`PLANNED.md updated (${entries.length} codetags).`);
	} else {
		console.log(`PLANNED.md already up to date (${entries.length} codetags).`);
	}
}

if (process.argv[1] && import.meta.url.endsWith(process.argv[1].split('/').pop())) {
	main();
}
